### ISSUE TITLE
After deploying to Azure login doesn't work

### ISSUE THREAD

**Issue by manmln** [elanderson/Angular-Core-IdentityServer#32]
Not sure if I did anything wrong. I tried all versions starting with 12. It works fine locally, I am able to log in, do debugging in VS 2017. When I deploy to Azure, there are issues:

- Identity server page has distorted layout, different from what I see at localhost:5000, there is missing top navigation bar. Here is URL: http://identityapp13.azurewebsites.net/home

- Clicking Login in ClientApp doesn't do anything. I tried to do remote debugging but for some reason I couldn't make it work (still learning Angular/bower/etc.). Here is URL: http://clientapp13.azurewebsites.net/home

- for version 15 ClientApp was not loading at all (error processing your request). Here is URL: http://clientapp15.azurewebsites.net/home

Please advise.
Thank you,
Michael

**Comment by manmln** [comment]
The first 2 issues was related to Content Security Policy. Changing references from remote sources of css and scripts to local resolved problem.

**Comment by elanderson** [comment]
Glad you found an answer to your first two item. Have you tried changing the ASPNETCORE_ENVIRONMENT environment var to Development to get more details on the third?

**Comment by manmln** [comment]
Yes, it is the same as #29. I didn't change the variable; it is still Development, but I get the message to change it on page. Sorry, I don't know what to do; I am  not so strong in latest technologies, haven't programmed for 12 years :(

**Comment by elanderson** [comment]
I closed #29 and opened this one back up since I believe they are different issues. 

When you publish to Azure the variable isn't set to development it is set to production. Check out [this](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments#azure) page on the docs for how to put the site into development mode. Once you do that we should get a more detailed error message that will help find the issue.

**Comment by manmln** [comment]
I set variable. This is what I see. Any suggestion what to try?

System.AggregateException: One or more errors occurred. (Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\local\Temp\4pjsgnvg.u42:83:19)
    at __webpack_require__ (D:\local\Temp\4pjsgnvg.u42:20:30)
    at createWebpackDevServer (D:\local\Temp\4pjsgnvg.u42:62:26)
    at D:\local\Temp\lgntfojf.pnm:114:19
    at IncomingMessage.<anonymous> (D:\local\Temp\lgntfojf.pnm:133:38)
    at emitNone (events.js:86:13)
Current directory is: D:\home\site\wwwroot
) ---> Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\local\Temp\4pjsgnvg.u42:83:19)
    at __webpack_require__ (D:\local\Temp\4pjsgnvg.u42:20:30)
    at createWebpackDevServer (D:\local\Temp\4pjsgnvg.u42:62:26)
    at D:\local\Temp\lgntfojf.pnm:114:19
    at IncomingMessage.<anonymous> (D:\local\Temp\lgntfojf.pnm:133:38)
    at emitNone (events.js:86:13)
Current directory is: D:\home\site\wwwroot

   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions options)
   at ClientApp.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Users\michael.lavatman\source\Workspaces\Angular-Core-IdentityServer-0.15.0\ClientApp\Startup.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass3_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
---> (Inner Exception #0) Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\local\Temp\4pjsgnvg.u42:83:19)
    at __webpack_require__ (D:\local\Temp\4pjsgnvg.u42:20:30)
    at createWebpackDevServer (D:\local\Temp\4pjsgnvg.u42:62:26)
    at D:\local\Temp\lgntfojf.pnm:114:19
    at IncomingMessage.<anonymous> (D:\local\Temp\lgntfojf.pnm:133:38)
    at emitNone (events.js:86:13)
Current directory is: D:\home\site\wwwroot

   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()<---

**Comment by elanderson** [comment]
Does anything in [this](https://github.com/aspnet/JavaScriptServices/issues/1212) help?

Try disabling server-side rendering and see if you still have a problem.

**Comment by manmln** [comment]
Whatever I did, didn't help

**Comment by elanderson** [comment]
What did you do?

Try putting the site back into production mode and see if there are any logs in Azure that might help give us a hint.

**Comment by elanderson** [comment]
I tried it and got the same issue. Seems to be related to [this](https://github.com/aspnet/JavaScriptServices/issues/1388). Looks like the solution is to recreate the client application using the new Angular CLI compatible template. I have added redoing the client app to my list.

**Comment by manmln** [comment]
I did fix the ClientApp site crash. 
But it generates an error:
Failed to load https://identityapp15.azurewebsites.net/.well-known/openid-configuration: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://clientapp15.azurewebsites.net' is therefore not allowed access.
And when clicking Login:
Well known endpoints must be loaded before user can login!
And this:
main.8a793f93b771dc4cf54e.bundle.js:1 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'login'

Also, as I mentioned before in label15 there are client side errors in Identity app:
Refused to load the stylesheet 'https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

identityapp15.azurewebsites.net/:11 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-eNYKgDOxdMjUMFmlqVjLSIBHYSBciCwh8Qq2QkPk7xA='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

identityapp15.azurewebsites.net/:1 Refused to load the script 'https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

identityapp15.azurewebsites.net/:166 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-dIkC+lnHXmVnIT5Z+EXzjiqO37UV46cPSb2V0TNQlxc='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

Thanks.
